travis:
  secure:
    BINSTAR_TOKEN: 3DcM8m+VomOn/gLNPxZO30er7t66mnQ1TINMmtF5NitNGaS20d69LlJyhsd7KGb7LSXAjiaoFkNDOrO3mPVJM1RSvBsazq8+NzBS8BJCLUK/gIjcRmd5VjT4hha6iO6PmMJ+vEOi/18XYNZbqYDj5AYvQm3UjQUZ8QoJ4oxlVCVVL9RAbF9I3LZII0G/f3oSC+3iFKhrd9I/Cefx/pniYohScBjh7/nMRwGtbw2m2NYGUxm4/r2usDh4FklhxtXYm3IBbKeEKhH1J/ZV/d6pSGoEN4NwfDELibGHFHqpF5YWMft5CtF2ThB6qlLKx7Rp4M1437rlcEUAajVLB08DtNJCeGXHoBJF7EHjqyC1y45VF1la3xv51Dvzhp0WmVIrGq6tG+c6+Lj8fRx204Qrn52wq4PDKHSOJvBKPMfjXgWWLP+dHQmAfpldlMQNI1BVwH3DpF/7zFGV85a38twNl2lqaxO/Fy1RNHc2fin+uTF7F4BQ2o2X6PkZXF0RBjBIVjF94u+Zh5nJGyO4YjVFe2ewVGwT2PJTuVe/Vp4/xlHTYS0El9grflNgvj4epFuV4SLwKtoXUB0CBFwAgJhUN29WfGZ6CyzW2DX9MqhoGl5zMgY2Vpvn3DjNPstHSI77mIxTsqPrqQxOqkU3+ES9LYyYb1gvYnEEsREYTO68bM0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
